const fs = require('fs');

// Test zeroed Fl items
const zeroedFl = [
  {no:1,key:"cement",legacyKeys:["cement_50kg"],category:"Cement",name:"Cement",nameSwahili:"Saruji (Mifuko)",unit:"bags",displayUnit:"50 kg bags",purchaseUnit:"50 kg bags",unitRatio:1,currentBalance:0,purchasePrice:0,reorderLevel:80,source:"Whole sallers",notes:"Cement is purchased as 50 kg bags."},
  {no:2,key:"mchanga_laini",legacyKeys:["sand_bucket"],category:"Mchanga (sand)",name:"Mchanga Laini",nameSwahili:"Mchanga Laini (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Msanga (27km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:3,key:"mchanga_mweupe",legacyKeys:[],category:"Mchanga (sand)",name:"Mchanga Mweupe",nameSwahili:"Mchanga Mweupe (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Msanga (27km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:4,key:"mchanga_mnene",legacyKeys:[],category:"Mchanga (sand)",name:"Mchanga Mnene",nameSwahili:"Mchanga Mnene (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Kikombo (21km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:5,key:"dust",legacyKeys:[],category:"Dust",name:"Dust",nameSwahili:"Dust / Vumbi (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Manchali (20km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:6,key:"chipping",legacyKeys:["chipping_bucket"],category:"Chipping",name:"Chipping",nameSwahili:"Chipping (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Manchali (20km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:7,key:"kokoto",legacyKeys:["aggregate_bucket"],category:"Kokoto / Aggregate",name:"Kokoto / Aggregate",nameSwahili:"Kokoto (Ndoo)",unit:"ndoo",displayUnit:"Trips (20 Cbm = 2,500 ndoo)",purchaseUnit:"Trip (20 Cbm)",unitRatio:2500,currentBalance:0,purchasePrice:0,reorderLevel:500,source:"Manchali (20km)",notes:"Purchase unit: Cbm, Inventory unit: Trip/Truck 20 Cbm = 2,500 ndoo"},
  {no:8,key:"dawa",legacyKeys:["chemical_liter"],category:"Chemical additive / hardener",name:"Dawa",nameSwahili:"Dawa ya Kuimarisha",unit:"Liters",displayUnit:"Barrels (200L each)",purchaseUnit:"Barrel of 200L",unitRatio:200,currentBalance:0,purchasePrice:0,reorderLevel:25,source:"Dar",notes:"Dawa is purchased as barrel of 200l each."},
  {no:9,key:"rangi_red",legacyKeys:["pigment_red_kg"],category:"Rangi",name:"Rangi Red",nameSwahili:"Rangi Nyekundu",unit:"kg",displayUnit:"Bags (25kg each)",purchaseUnit:"Bags of 25kg",unitRatio:25,currentBalance:0,purchasePrice:0,reorderLevel:15,source:"Dar",notes:"Rangi is purchased as bags of 25kg."},
  {no:10,key:"rangi_black",legacyKeys:["pigment_black_kg"],category:"Rangi",name:"Rangi Black",nameSwahili:"Rangi Nyeusi",unit:"kg",displayUnit:"Bags (25kg each)",purchaseUnit:"Bags of 25kg",unitRatio:25,currentBalance:0,purchasePrice:0,reorderLevel:10,source:"Dar",notes:"Rangi is purchased as bags of 25kg."},
  {no:11,key:"mafuta",legacyKeys:[],category:"Mafuta/oil",name:"Mafuta/oil",nameSwahili:"Mafuta / Oil",unit:"Liters",displayUnit:"Dumu (20L each)",purchaseUnit:"Dumu of 20L",unitRatio:20,currentBalance:0,purchasePrice:0,reorderLevel:20,source:"Shop",notes:"Mafuta/oil purchased as dumu of 20l."},
  {no:12,key:"steel_r6",legacyKeys:[],category:"Steel",name:"R6",nameSwahili:"Nondo R6",unit:"bars",displayUnit:"Pcs / Bars (12m)",purchaseUnit:"Pcs / Bars (12m)",unitRatio:1,currentBalance:0,purchasePrice:0,reorderLevel:20,source:"Shop / Wholesalers",notes:"Steel R6 reinforcement bars."},
  {no:13,key:"steel_10mm",legacyKeys:[],category:"Steel",name:"10mm",nameSwahili:"Nondo 10mm",unit:"bars",displayUnit:"Pcs / Bars (12m)",purchaseUnit:"Pcs / Bars (12m)",unitRatio:1,currentBalance:0,purchasePrice:0,reorderLevel:20,source:"Shop / Wholesalers",notes:"Steel 10mm reinforcement bars."}
];

console.log('Total items:', zeroedFl.length);
console.log('All quantities zero:', zeroedFl.every(m => m.currentBalance === 0));
console.log('All prices zero:', zeroedFl.every(m => m.purchasePrice === 0));
