const DEFAULT_MATERIAL_MASTER = [
  {
    no: 1,
    key: "cement",
    legacyKeys: ["cement_50kg"],
    category: "Cement",
    name: "Cement",
    source: "Whole sallers",
    purchaseUnit: "50 kg bags",
    unit: "bags",
    unitRatio: 1,
    currentBalance: 450,
    purchasePrice: 18500,
    reorderLevel: 80,
    notes: "Cement is purchased as 50 kg bags."
  },
  {
    no: 2,
    key: "mchanga_laini",
    legacyKeys: ["sand_bucket"],
    category: "Mchanga (sand)",
    name: "Mchanga Laini",
    source: "Msanga (27km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2500,
    purchasePrice: 350000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 3,
    key: "mchanga_mweupe",
    legacyKeys: [],
    category: "Mchanga (sand)",
    name: "Mchanga Mweupe",
    source: "Msanga (27km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2500,
    purchasePrice: 380000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 4,
    key: "mchanga_mnene",
    legacyKeys: [],
    category: "Mchanga (sand)",
    name: "Mchanga Mnene",
    source: "Kikombo (21km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2500,
    purchasePrice: 320000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 5,
    key: "dust",
    legacyKeys: [],
    category: "Dust",
    name: "Dust",
    source: "Manchali (20km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2500,
    purchasePrice: 280000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 6,
    key: "chipping",
    legacyKeys: ["chipping_bucket"],
    category: "Chipping",
    name: "Chipping",
    source: "Manchali (20km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2800,
    purchasePrice: 450000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 7,
    key: "kokoto",
    legacyKeys: ["aggregate_bucket"],
    category: "Kokoto / Aggregate",
    name: "Kokoto / Aggregate",
    source: "Manchali (20km)",
    purchaseUnit: "Trip (20 Cbm)",
    unit: "ndoo",
    displayUnit: "Trips (20 Cbm = 2,500 ndoo)",
    unitRatio: 2500,
    currentBalance: 2500,
    purchasePrice: 420000,
    reorderLevel: 500,
    notes: "Purchase unit: Cbm, Inventory unit: Trip/Truck (20 Cbm = 2,500 ndoo)"
  },
  {
    no: 8,
    key: "dawa",
    legacyKeys: ["chemical_liter"],
    category: "Chemical additive / hardener",
    name: "Dawa",
    source: "Dar",
    purchaseUnit: "Barrel of 200L",
    unit: "Liters",
    displayUnit: "Barrels (200L each)",
    unitRatio: 200,
    currentBalance: 200,
    purchasePrice: 480000,
    reorderLevel: 25,
    notes: "Dawa is purchased as barrel of 200l each."
  },
  {
    no: 9,
    key: "rangi_red",
    legacyKeys: ["pigment_red_kg"],
    category: "Rangi",
    name: "Rangi Red",
    source: "Dar",
    purchaseUnit: "Bags of 25kg",
    unit: "kg",
    displayUnit: "Bags (25kg each)",
    unitRatio: 25,
    currentBalance: 75,
    purchasePrice: 85000,
    reorderLevel: 15,
    notes: "Rangi is purchased as bags of 25kg."
  },
  {
    no: 10,
    key: "rangi_black",
    legacyKeys: ["pigment_black_kg"],
    category: "Rangi",
    name: "Rangi Black",
    source: "Dar",
    purchaseUnit: "Bags of 25kg",
    unit: "kg",
    displayUnit: "Bags (25kg each)",
    unitRatio: 25,
    currentBalance: 50,
    purchasePrice: 95000,
    reorderLevel: 10,
    notes: "Rangi is purchased as bags of 25kg."
  },
  {
    no: 11,
    key: "mafuta",
    legacyKeys: [],
    category: "Mafuta/oil",
    name: "Mafuta/oil",
    source: "Shop",
    purchaseUnit: "Dumu of 20L",
    unit: "Liters",
    displayUnit: "Dumu (20L each)",
    unitRatio: 20,
    currentBalance: 40,
    purchasePrice: 70000,
    reorderLevel: 20,
    notes: "Mafuta/oil purchased as dumu of 20l."
  },
  {
    no: 12,
    key: "steel_r6",
    legacyKeys: [],
    category: "Steel",
    name: "R6",
    source: "Shop / Wholesalers",
    purchaseUnit: "Pcs / Bars (12m)",
    unit: "bars",
    displayUnit: "Pcs / Bars",
    unitRatio: 1,
    currentBalance: 60,
    purchasePrice: 12500,
    reorderLevel: 20,
    notes: "Steel R6 reinforcement bars."
  },
  {
    no: 13,
    key: "steel_10mm",
    legacyKeys: [],
    category: "Steel",
    name: "10mm",
    source: "Shop / Wholesalers",
    purchaseUnit: "Pcs / Bars (12m)",
    unit: "bars",
    displayUnit: "Pcs / Bars",
    unitRatio: 1,
    currentBalance: 40,
    purchasePrice: 24000,
    reorderLevel: 20,
    notes: "Steel 10mm reinforcement bars."
  }
];

console.log('Total materials:', DEFAULT_MATERIAL_MASTER.length);
DEFAULT_MATERIAL_MASTER.forEach(m => {
  console.log(`${m.no}. [${m.category}] ${m.name} | ${m.purchaseUnit} | Source: ${m.source} | Price: ${m.purchasePrice} Tsh | Qty: ${m.currentBalance} ${m.unit}`);
});
